countries = {1: "spain", 2: "england", 3: "germany", 4: "italy", 5: "france"}

leagues = {
    "spain": {
        "name": "La Liga Santander",
        "teams": [
            "Real Madrid",
            "FC Barcelona",
            "Valencia CF",
            "Atlético Madrid",
            "RC Celta",
            "Real Betis",
            "Villarreal CF",
            "Real Sociedad",
            "Athletic Club de Bilbao",
            "Deportivo Alavés",
            "Getafe CF",
            "Sevilla FC",
            "Levante UD",
            "Granada CF",
            "CA Osasuna",
            "Real Valladolid CF",
            "RCD Espanyol",
            "SD Eibar",
            "RCD Mallorca",
            "CD Leganés",
        ],
    },
    "england": {
        "name": "English Premier League",
        "teams": [
            "Arsenal",
            "Bournemouth",
            "Brighton & Hove Albion",
            "Burnley",
            "Sheffield United",
            "Chelsea",
            "Crystal Palace",
            "Everton",
            "Norwich City",
            "Aston Villa",
            "Leicester City",
            "Liverpool",
            "Manchester City",
            "Manchester United",
            "Newcastle United",
            "Southampton",
            "Tottenham Hotspur",
            "Watford",
            "West Ham United",
            "Wolverhampton Wanderers",
        ],
    },
    "germany": {
        "name": "Bundesliga",
        "teams": [
            "FC Bayern München",
            "Borussia Dortmund",
            "Bayer 04 Leverkusen",
            "RB Leipzig",
            "Eintracht Frankfurt",
            "TSG 1899 Hoffenheim",
            "1. FC Köln",
            "Borussia Mönchengladbach",
            "SV Werder Bremen",
            "Hertha BSC",
            "VfL Wolfsburg",
            "FC Schalke 04",
            "SC Freiburg",
            "FC Augsburg",
            "1. FSV Mainz 05",
            "1. FC Union Berlin",
            "Fortuna Düsseldorf",
            "SC Paderborn 07",
        ],
    },
    "italy": {
        "name": "Seria A",
        "teams": [
            "Juventus",
            "Napoli",
            "Lazio",
            "Milan",
            "Torino",
            "Sampdoria",
            "Inter",
            "Brescia",
            "Cagliari",
            "Sassuolo",
            "Roma",
            "Fiorentina",
            "Genoa",
            "Atalanta",
            "Bologna",
            "SPAL",
            "Udinese",
            "Hellas Verona",
            "Parma",
            "Lecce",
        ],
    },
    "france": {
        "name": "Ligue 1",
        "teams": [
            "Paris Saint-Germain",
            "AS Saint-Étienne",
            "Olympique de Marseille",
            "AS Monaco",
            "Olympique Lyonnais",
            "FC Girondins de Bordeaux",
            "LOSC Lille",
            "FC Nantes",
            "RC Strasbourg Alsace",
            "Montpellier HSC",
            "Angers SCO",
            "OGC Nice",
            "Stade Rennais FC",
            "Nîmes Olympique",
            "Toulouse Football Club",
            "FC Metz",
            "Amiens SC",
            "Stade de Reims",
            "Dijon FCO",
            "Stade Brestois 29",
        ],
    },
}
