names = [
    "Lucas Merino",
    "Jonas Klavan",
    "James Prödl",
    "Cenk Gallagher",
    "David Junior Iheanacho",
    "Sam Defour",
    "Aaron Halford",
    "Cesc Zinchenko",
    "Maya Johnson",
    "Danny Ampadu",
    "Kyle Ofoborh",
    "Arijanet Sterling",
    "Dwight Diakhaby",
    "Jack Caballero",
    "Joel Bertrand",
    "Christian Zouma",
    "Dwight Iwobi",
    "Danilo Luiz Valery",
    "Matty Valery",
    "Alireza Cahill",
    "Etienne Nordtveit",
    "Kevin Pereira Gomes",
    "Beni Diangana",
    "Marko Meyer",
    "Nathaniel Ogbonna",
    "Sokratis Llorente",
    "Tyreke Hendrick",
    "Filip Okazaki",
    "Wesley Bonatini",
    "Laurent Palmieri dos Santos",
    "Beni Cahill",
    "Vicente Rose",
    "Matthew Martínez",
    "Vicente Richards",
    "Hélder Courtois",
    "Javier Jiménez",
    "Cheikhou Walcott",
    "Nacho Henderson",
    "Tim Gomes",
    "Scott Mendez-Laing",
    "Will Agosto Ramírez",
    "Jesse Kachunga",
    "Juninho Nketiah",
    "Ben Townsend",
    "Mamadou Diamé",
    "Matteo Surridge",
    "Theo Martínez",
    "Alexandre Nascimento Smalling",
    "Matt Forster",
    "Robbie Mendy",
    "Ryan Alexander-Arnold",
    "Bonatini Lohner Maia Diaz",
    "Terence Xhaka",
    "Morgan Santana de Moraes",
    "Manolo Duhaney",
    "Sead Rico",
    "Cheikhou Bryan",
    "Kyle Byram",
    "Willian Elyounoussi",
    "Max Mawson",
    "Ryan Kolasinac",
    "Mathias Norris",
    "Vincent Davies",
    "Olivier Ward-Prowse",
    "Fraser Leno",
    "Ander Sturridge",
    "Christian Francis",
    "Alexandre Nascimento Bednarek",
    "Viktor Capoue",
    "Younes Simpson",
    "Tyreke Lamela",
    "James Mawson",
    "Naby Jagielka",
    "Ayoze Nkoudou",
    "José Diogo Murphy",
    "Marvin Boufal",
    "Kyle Mousset",
    "Alex Pereira",
    "Davy Matic",
    "Robbie Marsh",
    "Antonio Sánchez",
    "Stefano Kaboul",
    "Timothy Clark",
    "Paulo San Miguel del Castillo",
    "Chris Masina",
    "Morgan Amartey",
    "James Cavaleiro",
    "Alfie Mepham",
    "Daniel Sterling",
    "Laurent Romeu Vidal",
    "Beni Alonso",
    "Nahki Nunes do Nascimento",
    "Nemanja Nkoudou",
    "Jason van Aanholt",
    "Angel Murray",
    "Ben John",
    "Dwight Guaita",
    "Dan Mendez-Laing",
    "Carlos Cork",
    "Ryan Holgate",
]

formations = [
    [1, 4, 5],
    [1, 5, 4],
    [2, 3, 5],
    [2, 4, 4],
    [2, 5, 3],
    [3, 2, 5],
    [3, 3, 4],
    [3, 4, 3],
]
